[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bucex"
version = "0.3.3"
description = "Bayesian Unobserved Components for Extremes"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Bas"}]
dependencies = [
  "numpy",
  "scipy",
  "pandas",
  "matplotlib",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["bucex*"]
